#!/usr/bin/env bash

GETH=$HOME/projects/ethereum/go-ethereum/build/bin/geth
GETHOPTS=''
echo $GETHOPTS

case $1 in
  start)
    echo "Starting testnet node"
    #$GETH --genesis ./testnet/genesis.json --datadir ./testnet --minerthreads 1 --mine --vmdebug --rpc --ipcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 js unlock.js 2>> /tmp/digix_testnet.out
    $GETH --nat "none" --datadir ./testnet --minerthreads 1 --mine --rpc --ipcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 console 2>> /tmp/digix_testnet.out
    ;;
  attach)
    echo "Attaching to console"
    $GETH --datadir ./testnet --rpc --ipcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3 attach
    ;;
  clear)
    echo "Clearing testnet files"
    cat /dev/null > /tmp/digix_testnet.out
    data_files=(testnet/chaindata testnet/dapp testnet/geth.ipc testnet/nodekey testnet/nodes)
    for data_file in ${data_files[@]}
    do
      rm -rf $data_file
    done
    $GETH --datadir ./testnet init ./testnet/genesis.json
    ;;
  *)
    echo "Usage $0 [start | clear | attach]"
    ;;
esac

